name: EC2-Control

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose Action"
        required: true
        default: start
        type: choice
        options:
          - start
          - stop

jobs:
  control-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

########################################## START EC2 ##########################################

      #Start EC2
      - name: Start EC2 
        if: ${{ github.event.inputs.action == 'start' }}
        run: |
          echo "Starting EC2 instance..."
          aws ec2 start-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }}

          echo "Waiting for instance to be running..."
          aws ec2 wait instance-running --instance-ids ${{ secrets.EC2_INSTANCE_ID }}

          echo "Getting public IP..."
          PUBLIC_IP=$(aws ec2 describe-instances \
          --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
          --query "Reservations[0].Instances[0].PublicIpAddress" \
          --output text)

          echo "Public IPv4: $PUBLIC_IP"

          # Export to GitHub environment so next step can use it
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
          echo "::set-output name=PUBLIC_IP::$PUBLIC_IP"

      #Check the Status if the n8n container is running
      - name: Check the status of n8n-container
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        if: ${{ github.event.inputs.action == 'start' }}
        run: | 
          echo "$EC2_SSH_KEY" > pem.key
          chmod 400 pem.key

          #Wait for the instance to be running
          sleep 15

          echo "Checking Running Containers"
          N8N_STATUS=$(ssh -o StrictHostKeyChecking=no -i pem.key ubuntu@${{ env.PUBLIC_IP }} '
            if [ "$(docker ps -q -f name=n8n)" ]; then
              echo "n8n Container is Already Running"
            else
              echo "n8n Container is Not Running. Starting it..."
              docker start n8n
              echo "n8n Container is Now Started"
            fi
          ' | tr '\n' ' ')

          # Export to GitHub environment
          echo "DOCKER_INFO=$N8N_STATUS" >> $GITHUB_ENV

          #Pipeline only, shows all running containers
          ssh -o StrictHostKeyChecking=no -i pem.key ubuntu@${{ env.PUBLIC_IP }} "docker ps"
      
      #Send Email Notification via Gmail if EC2 is started
      - name: Send Email Notification (Start)
        uses: dawidd6/action-send-mail@v3
        if: ${{ github.event.inputs.action == 'start' }}
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: EC2 Instance Notification
          to: ${{ secrets.EMAIL_TO }}
          from: GitHub Actions
          body: |
            GitHub Actions Triggered 
            ==========================================
            Repository: n8n-automation
            ==========================================
            EC2 Instance: TURNED ON
            ==========================================
            PUBLIC IPv4: ${{ env.PUBLIC_IP }}
            ==========================================
            Docker Containers Status:
            ${{ env.DOCKER_INFO }}
            ==========================================

            Triggered by: ${{ github.actor }} via GitHub Actions pipeline.

########################################## STOP EC2 ##########################################

      #Stop EC2
      - name: Stop EC2
        if: ${{ github.event.inputs.action == 'stop' }}
        run: | 
          aws ec2 stop-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }}

      #Send Email Notification via Gmail if EC2 is stopped
      - name: Send Email Notification (Stop)
        if: ${{ github.event.inputs.action == 'stop' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: EC2 Instance Notification
          to: ${{ secrets.EMAIL_TO }}
          from: GitHub Actions
          body: |
            GitHub Actions Triggered 
            ==========================================
            Repository: n8n-automation
            ==========================================
            EC2 Instance: STOPPED
            ==========================================

            Triggered by: ${{ github.actor }} via GitHub Actions pipeline.